# golangci-lint configuration with security-first settings
# For an authentication server, we enable strict security linters

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
  skip-dirs:
    - vendor
    - examples
    - frontend
    - clients/generated
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck      # Check error handling
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis
    - unused        # Check for unused code
    
    # Security linters (CRITICAL for auth server)
    - gosec         # Go security checker - SQL injection, hardcoded secrets, etc.
    
    # Code quality (affects security indirectly)
    - gocyclo       # Cyclomatic complexity
    - gofmt         # Formatting
    - goimports     # Import formatting
    - misspell      # Spelling
    - revive        # Fast linter
    - stylecheck    # Style issues
    - typecheck     # Type checking
    - unconvert     # Unnecessary type conversions
    - unparam       # Unused function parameters
    - goconst       # Repeated strings that could be constants
    - gocritic      # Comprehensive linter
    - gocognit      # Cognitive complexity
    - bodyclose     # HTTP response body close
    - noctx         # HTTP requests without context
    - rowserrcheck  # SQL rows.Err() check
    - sqlclosecheck # SQL Close() check
    - exportloopref # Loop variable exported incorrectly
    - errname       # Error naming conventions
    - errorlint     # Error wrapping
    - nilnil        # Return nil, nil
    - nilerr        # Return nil error
    - prealloc      # Pre-allocate slices
    - predeclared   # Shadowed predeclared identifiers
    - wastedassign  # Wasted assignments
    
  disable:
    - funlen        # We'll rely on gocyclo for complexity
    - lll           # Line length - not critical for security
    - gomnd         # Magic numbers - debatable

linters-settings:
  # GOSEC - Critical for auth server security
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Audit errors not checked - we use errcheck for this
    config:
      global:
        # SQL injection patterns
        G201: "sql"
        # Hardcoded credentials
        G101: "password|passwd|token|secret|key"
      # Check for weak crypto
      G401: true
      # Check for weak random
      G404: true
      # Check for directory traversal
      G304: true
      # Check for command injection  
      G204: true
  
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - io.Copy(*os.File)
      - io.Close(*os.File)
      - (*database/sql.Rows).Close
      - fmt.Fprintf
      - fmt.Fprintln
  
  govet:
    check-shadowing: true
    enable-all: true
  
  gocyclo:
    min-complexity: 15  # Lower is stricter
  
  gocognit:
    min-complexity: 20  # Cognitive complexity
  
  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
          - sayRepetitiveInsteadOfStutters
      - name: package-comments
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
      - name: superfluous-else
      - name: modifies-parameter
      - name: unreachable-code
      - name: time-naming
      - name: var-declaration
      - name: unexported-return
      - name: errorf
      - name: blank-imports
      - name: range-val-in-closure
      - name: range-val-address
      - name: waitgroup-by-value
      - name: atomic
      - name: empty-lines
      - name: call-to-gc
      - name: duplicated-imports
      - name: import-shadowing
      - name: bare-return
      - name: unused-parameter
      - name: unused-receiver
      - name: early-return
      - name: defer
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - unnamedResult
      - hugeParam  # We'll handle this case by case
  
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]  # Allow underscores in names for some cases

issues:
  exclude-rules:
    # Exclude test files from some checks
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - gocyclo
        - gocognit
    
    # Exclude generated code
    - path: clients/generated/
      linters:
        - all
    
    # Exclude examples from strict checks
    - path: examples/
      linters:
        - gosec
        - errcheck
    
    # Exclude migration files from unused checks
    - path: migrations/
      linters:
        - unused
  
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text
  max-same-issues: 0
  
  # Show all issues
  new: false
  
  # Report any suspicious comments
  exclude-use-default: false

severity:
  default-severity: warning
  rules:
    - linters:
        - gosec
      severity: error  # Security issues are errors
    - linters:
        - errcheck
      severity: error  # Unhandled errors are critical

