// Code generated by authsome sdkgen. DO NOT EDIT.

import type {
  APIKey,
  AuthResponse,
  Device,
  Error,
  Invitation,
  MFAEnrollment,
  Manifest,
  Member,
  Organization,
  Session,
  TokenResponse,
  User,
  AdminBanUserRequest,
  ChangePasswordRequest,
  ForgotPasswordRequest,
  CreateAPIKeyRequest,
  MagicLinkSendRequest,
  MagicLinkVerifyRequest,
  UpdateMeRequest,
  MfaChallengeRequest,
  MfaEnrollRequest,
  MfaRecoveryVerifyRequest,
  MfaSMSSendRequest,
  MfaSMSVerifyRequest,
  MfaVerifyRequest,
  CreateOrgRequest,
  UpdateOrgRequest,
  CreateInvitationRequest,
  AddMemberRequest,
  RefreshSessionRequest,
  ResetPasswordRequest,
  SignInRequest,
  SignUpRequest,
  SsoACSRequest,
  SsoCallbackRequest,
  VerifyEmailRequest,
} from './types';

export interface AuthClientConfig {
  /** Base URL of the AuthSome API (e.g., "https://api.example.com") */
  baseURL: string;
  /** Optional session token for authenticated requests */
  token?: string;
  /** Optional custom fetch implementation */
  fetch?: typeof globalThis.fetch;
}

export class AuthClient {
  private baseURL: string;
  private token: string | undefined;
  private fetchFn: typeof globalThis.fetch;

  constructor(config: AuthClientConfig) {
    this.baseURL = config.baseURL.replace(/\/+$/, '');
    this.token = config.token;
    this.fetchFn = config.fetch ?? globalThis.fetch.bind(globalThis);
  }

  /** Set the session token for authenticated requests. */
  setToken(token: string | undefined): void {
    this.token = token;
  }

  /** Get the current session token. */
  getToken(): string | undefined {
    return this.token;
  }

  // ──────────────────────────────────────────────────
  // Generated methods
  // ──────────────────────────────────────────────────

  /**
   * API manifest
   * GET /.well-known/authsome/manifest
   */
  async getManifest(): Promise<Manifest> {
    const path = "/.well-known/authsome/manifest";
    return this.request<Manifest>(
      'GET',
      path,
      undefined,
    );
  }

  /**
   * OpenAPI specification
   * GET /.well-known/authsome/openapi
   */
  async getOpenAPISpec(): Promise<void> {
    const path = "/.well-known/authsome/openapi";
    return this.request<void>(
      'GET',
      path,
      undefined,
    );
  }

  /**
   * Stop impersonation (admin)
   * POST /v1/admin/impersonate/stop
   */
  async adminStopImpersonation(): Promise<Record<string, unknown>> {
    const path = "/v1/admin/impersonate/stop";
    return this.request<Record<string, unknown>>(
      'POST',
      path,
      undefined,
    );
  }

  /**
   * Impersonate user (admin)
   * POST /v1/admin/impersonate/{userId}
   */
  async adminImpersonate(userId: string): Promise<AuthResponse> {
    const path = `/v1/admin/impersonate/${userId}`;
    return this.request<AuthResponse>(
      'POST',
      path,
      undefined,
    );
  }

  /**
   * List all users (admin)
   * GET /v1/admin/users
   */
  async adminListUsers(limit?: number, offset?: number): Promise<Record<string, unknown>> {
    const params = new URLSearchParams();
    if (limit !== undefined) params.set('limit', String(limit));
    if (offset !== undefined) params.set('offset', String(offset));
    const qs = params.toString();
    const path = "/v1/admin/users" + (qs ? `?${qs}` : '');
    return this.request<Record<string, unknown>>(
      'GET',
      path,
      undefined,
    );
  }

  /**
   * Get user (admin)
   * GET /v1/admin/users/{userId}
   */
  async adminGetUser(userId: string): Promise<User> {
    const path = `/v1/admin/users/${userId}`;
    return this.request<User>(
      'GET',
      path,
      undefined,
    );
  }

  /**
   * Delete user (admin)
   * DELETE /v1/admin/users/{userId}
   */
  async adminDeleteUser(userId: string): Promise<Record<string, unknown>> {
    const path = `/v1/admin/users/${userId}`;
    return this.request<Record<string, unknown>>(
      'DELETE',
      path,
      undefined,
    );
  }

  /**
   * Ban user (admin)
   * POST /v1/admin/users/{userId}/ban
   */
  async adminBanUser(userId: string, body: AdminBanUserRequest): Promise<Record<string, unknown>> {
    const path = `/v1/admin/users/${userId}/ban`;
    return this.request<Record<string, unknown>>(
      'POST',
      path,
      body,
    );
  }

  /**
   * Unban user (admin)
   * POST /v1/admin/users/{userId}/unban
   */
  async adminUnbanUser(userId: string): Promise<Record<string, unknown>> {
    const path = `/v1/admin/users/${userId}/unban`;
    return this.request<Record<string, unknown>>(
      'POST',
      path,
      undefined,
    );
  }

  /**
   * Change password
   * POST /v1/auth/change-password
   */
  async changePassword(body: ChangePasswordRequest): Promise<Record<string, unknown>> {
    const path = "/v1/auth/change-password";
    return this.request<Record<string, unknown>>(
      'POST',
      path,
      body,
    );
  }

  /**
   * List devices
   * GET /v1/auth/devices
   */
  async listDevices(): Promise<Record<string, unknown>> {
    const path = "/v1/auth/devices";
    return this.request<Record<string, unknown>>(
      'GET',
      path,
      undefined,
    );
  }

  /**
   * Delete device
   * DELETE /v1/auth/devices/{deviceId}
   */
  async deleteDevice(deviceId: string): Promise<Record<string, unknown>> {
    const path = `/v1/auth/devices/${deviceId}`;
    return this.request<Record<string, unknown>>(
      'DELETE',
      path,
      undefined,
    );
  }

  /**
   * Request password reset
   * POST /v1/auth/forgot-password
   */
  async forgotPassword(body: ForgotPasswordRequest): Promise<Record<string, unknown>> {
    const path = "/v1/auth/forgot-password";
    return this.request<Record<string, unknown>>(
      'POST',
      path,
      body,
    );
  }

  /**
   * Health check
   * GET /v1/auth/health
   */
  async healthCheck(): Promise<Record<string, unknown>> {
    const path = "/v1/auth/health";
    return this.request<Record<string, unknown>>(
      'GET',
      path,
      undefined,
    );
  }

  /**
   * List API keys
   * GET /v1/auth/keys
   */
  async listAPIKeys(): Promise<Record<string, unknown>> {
    const path = "/v1/auth/keys";
    return this.request<Record<string, unknown>>(
      'GET',
      path,
      undefined,
    );
  }

  /**
   * Create API key
   * POST /v1/auth/keys
   */
  async createAPIKey(body: CreateAPIKeyRequest): Promise<Record<string, unknown>> {
    const path = "/v1/auth/keys";
    return this.request<Record<string, unknown>>(
      'POST',
      path,
      body,
    );
  }

  /**
   * Revoke API key
   * DELETE /v1/auth/keys/{keyId}
   */
  async revokeAPIKey(keyId: string): Promise<Record<string, unknown>> {
    const path = `/v1/auth/keys/${keyId}`;
    return this.request<Record<string, unknown>>(
      'DELETE',
      path,
      undefined,
    );
  }

  /**
   * Send magic link email
   * POST /v1/auth/magic-link/send
   */
  async magicLinkSend(body: MagicLinkSendRequest): Promise<Record<string, unknown>> {
    const path = "/v1/auth/magic-link/send";
    return this.request<Record<string, unknown>>(
      'POST',
      path,
      body,
    );
  }

  /**
   * Verify magic link token
   * POST /v1/auth/magic-link/verify
   */
  async magicLinkVerify(body: MagicLinkVerifyRequest): Promise<AuthResponse> {
    const path = "/v1/auth/magic-link/verify";
    return this.request<AuthResponse>(
      'POST',
      path,
      body,
    );
  }

  /**
   * Get current user
   * GET /v1/auth/me
   */
  async getMe(): Promise<User> {
    const path = "/v1/auth/me";
    return this.request<User>(
      'GET',
      path,
      undefined,
    );
  }

  /**
   * Update current user profile
   * PATCH /v1/auth/me
   */
  async updateMe(body: UpdateMeRequest): Promise<User> {
    const path = "/v1/auth/me";
    return this.request<User>(
      'PATCH',
      path,
      body,
    );
  }

  /**
   * Delete account (self-service)
   * DELETE /v1/auth/me
   */
  async deleteAccount(): Promise<Record<string, unknown>> {
    const path = "/v1/auth/me";
    return this.request<Record<string, unknown>>(
      'DELETE',
      path,
      undefined,
    );
  }

  /**
   * Export user data (GDPR)
   * GET /v1/auth/me/export
   */
  async exportUserData(): Promise<Record<string, unknown>> {
    const path = "/v1/auth/me/export";
    return this.request<Record<string, unknown>>(
      'GET',
      path,
      undefined,
    );
  }

  /**
   * Complete MFA challenge
   * POST /v1/auth/mfa/challenge
   */
  async mfaChallenge(body: MfaChallengeRequest): Promise<AuthResponse> {
    const path = "/v1/auth/mfa/challenge";
    return this.request<AuthResponse>(
      'POST',
      path,
      body,
    );
  }

  /**
   * Enroll in MFA
   * POST /v1/auth/mfa/enroll
   */
  async mfaEnroll(body: MfaEnrollRequest): Promise<MFAEnrollment> {
    const path = "/v1/auth/mfa/enroll";
    return this.request<MFAEnrollment>(
      'POST',
      path,
      body,
    );
  }

  /**
   * Verify MFA recovery code
   * POST /v1/auth/mfa/recovery/verify
   */
  async mfaRecoveryVerify(body: MfaRecoveryVerifyRequest): Promise<AuthResponse> {
    const path = "/v1/auth/mfa/recovery/verify";
    return this.request<AuthResponse>(
      'POST',
      path,
      body,
    );
  }

  /**
   * Send SMS verification code
   * POST /v1/auth/mfa/sms/send
   */
  async mfaSMSSend(body: MfaSMSSendRequest): Promise<Record<string, unknown>> {
    const path = "/v1/auth/mfa/sms/send";
    return this.request<Record<string, unknown>>(
      'POST',
      path,
      body,
    );
  }

  /**
   * Verify SMS code
   * POST /v1/auth/mfa/sms/verify
   */
  async mfaSMSVerify(body: MfaSMSVerifyRequest): Promise<Record<string, unknown>> {
    const path = "/v1/auth/mfa/sms/verify";
    return this.request<Record<string, unknown>>(
      'POST',
      path,
      body,
    );
  }

  /**
   * Verify MFA code
   * POST /v1/auth/mfa/verify
   */
  async mfaVerify(body: MfaVerifyRequest): Promise<Record<string, unknown>> {
    const path = "/v1/auth/mfa/verify";
    return this.request<Record<string, unknown>>(
      'POST',
      path,
      body,
    );
  }

  /**
   * List user organizations
   * GET /v1/auth/orgs
   */
  async listOrgs(): Promise<Record<string, unknown>> {
    const path = "/v1/auth/orgs";
    return this.request<Record<string, unknown>>(
      'GET',
      path,
      undefined,
    );
  }

  /**
   * Create organization
   * POST /v1/auth/orgs
   */
  async createOrg(body: CreateOrgRequest): Promise<Organization> {
    const path = "/v1/auth/orgs";
    return this.request<Organization>(
      'POST',
      path,
      body,
    );
  }

  /**
   * Get organization
   * GET /v1/auth/orgs/{orgId}
   */
  async getOrg(orgId: string): Promise<Organization> {
    const path = `/v1/auth/orgs/${orgId}`;
    return this.request<Organization>(
      'GET',
      path,
      undefined,
    );
  }

  /**
   * Update organization
   * PATCH /v1/auth/orgs/{orgId}
   */
  async updateOrg(orgId: string, body: UpdateOrgRequest): Promise<Organization> {
    const path = `/v1/auth/orgs/${orgId}`;
    return this.request<Organization>(
      'PATCH',
      path,
      body,
    );
  }

  /**
   * Delete organization
   * DELETE /v1/auth/orgs/{orgId}
   */
  async deleteOrg(orgId: string): Promise<Record<string, unknown>> {
    const path = `/v1/auth/orgs/${orgId}`;
    return this.request<Record<string, unknown>>(
      'DELETE',
      path,
      undefined,
    );
  }

  /**
   * List organization invitations
   * GET /v1/auth/orgs/{orgId}/invitations
   */
  async listInvitations(orgId: string): Promise<Record<string, unknown>> {
    const path = `/v1/auth/orgs/${orgId}/invitations`;
    return this.request<Record<string, unknown>>(
      'GET',
      path,
      undefined,
    );
  }

  /**
   * Create organization invitation
   * POST /v1/auth/orgs/{orgId}/invitations
   */
  async createInvitation(orgId: string, body: CreateInvitationRequest): Promise<Invitation> {
    const path = `/v1/auth/orgs/${orgId}/invitations`;
    return this.request<Invitation>(
      'POST',
      path,
      body,
    );
  }

  /**
   * List organization members
   * GET /v1/auth/orgs/{orgId}/members
   */
  async listMembers(orgId: string): Promise<Record<string, unknown>> {
    const path = `/v1/auth/orgs/${orgId}/members`;
    return this.request<Record<string, unknown>>(
      'GET',
      path,
      undefined,
    );
  }

  /**
   * Add organization member
   * POST /v1/auth/orgs/{orgId}/members
   */
  async addMember(orgId: string, body: AddMemberRequest): Promise<Member> {
    const path = `/v1/auth/orgs/${orgId}/members`;
    return this.request<Member>(
      'POST',
      path,
      body,
    );
  }

  /**
   * Remove organization member
   * DELETE /v1/auth/orgs/{orgId}/members/{memberId}
   */
  async removeMember(orgId: string, memberId: string): Promise<Record<string, unknown>> {
    const path = `/v1/auth/orgs/${orgId}/members/${memberId}`;
    return this.request<Record<string, unknown>>(
      'DELETE',
      path,
      undefined,
    );
  }

  /**
   * Refresh session tokens
   * POST /v1/auth/refresh
   */
  async refreshSession(body: RefreshSessionRequest): Promise<TokenResponse> {
    const path = "/v1/auth/refresh";
    return this.request<TokenResponse>(
      'POST',
      path,
      body,
    );
  }

  /**
   * Resend email verification
   * POST /v1/auth/resend-verification
   */
  async resendVerification(): Promise<Record<string, unknown>> {
    const path = "/v1/auth/resend-verification";
    return this.request<Record<string, unknown>>(
      'POST',
      path,
      undefined,
    );
  }

  /**
   * Reset password with token
   * POST /v1/auth/reset-password
   */
  async resetPassword(body: ResetPasswordRequest): Promise<Record<string, unknown>> {
    const path = "/v1/auth/reset-password";
    return this.request<Record<string, unknown>>(
      'POST',
      path,
      body,
    );
  }

  /**
   * List active sessions
   * GET /v1/auth/sessions
   */
  async listSessions(): Promise<Record<string, unknown>> {
    const path = "/v1/auth/sessions";
    return this.request<Record<string, unknown>>(
      'GET',
      path,
      undefined,
    );
  }

  /**
   * Revoke a session
   * DELETE /v1/auth/sessions/{id}
   */
  async revokeSession(id: string): Promise<Record<string, unknown>> {
    const path = `/v1/auth/sessions/${id}`;
    return this.request<Record<string, unknown>>(
      'DELETE',
      path,
      undefined,
    );
  }

  /**
   * Sign in with credentials
   * POST /v1/auth/signin
   */
  async signIn(body: SignInRequest): Promise<AuthResponse> {
    const path = "/v1/auth/signin";
    return this.request<AuthResponse>(
      'POST',
      path,
      body,
    );
  }

  /**
   * Sign out (revoke session)
   * POST /v1/auth/signout
   */
  async signOut(): Promise<Record<string, unknown>> {
    const path = "/v1/auth/signout";
    return this.request<Record<string, unknown>>(
      'POST',
      path,
      undefined,
    );
  }

  /**
   * Sign up a new user
   * POST /v1/auth/signup
   */
  async signUp(body: SignUpRequest): Promise<AuthResponse> {
    const path = "/v1/auth/signup";
    return this.request<AuthResponse>(
      'POST',
      path,
      body,
    );
  }

  /**
   * Start social OAuth flow
   * POST /v1/auth/social/{provider}
   */
  async socialStart(provider: string): Promise<Record<string, unknown>> {
    const path = `/v1/auth/social/${provider}`;
    return this.request<Record<string, unknown>>(
      'POST',
      path,
      undefined,
    );
  }

  /**
   * OAuth callback
   * GET /v1/auth/social/{provider}/callback
   */
  async socialCallback(provider: string, code: string, state: string): Promise<AuthResponse> {
    const params = new URLSearchParams();
    if (code !== undefined) params.set('code', String(code));
    if (state !== undefined) params.set('state', String(state));
    const qs = params.toString();
    const path = `/v1/auth/social/${provider}/callback` + (qs ? `?${qs}` : '');
    return this.request<AuthResponse>(
      'GET',
      path,
      undefined,
    );
  }

  /**
   * SSO SAML ACS endpoint
   * POST /v1/auth/sso/{provider}/acs
   */
  async ssoACS(provider: string, body: SsoACSRequest): Promise<AuthResponse> {
    const path = `/v1/auth/sso/${provider}/acs`;
    return this.request<AuthResponse>(
      'POST',
      path,
      body,
    );
  }

  /**
   * SSO OIDC callback
   * POST /v1/auth/sso/{provider}/callback
   */
  async ssoCallback(provider: string, body: SsoCallbackRequest): Promise<AuthResponse> {
    const path = `/v1/auth/sso/${provider}/callback`;
    return this.request<AuthResponse>(
      'POST',
      path,
      body,
    );
  }

  /**
   * Start SSO login flow
   * POST /v1/auth/sso/{provider}/login
   */
  async ssoLogin(provider: string): Promise<Record<string, unknown>> {
    const path = `/v1/auth/sso/${provider}/login`;
    return this.request<Record<string, unknown>>(
      'POST',
      path,
      undefined,
    );
  }

  /**
   * Verify email address
   * POST /v1/auth/verify-email
   */
  async verifyEmail(body: VerifyEmailRequest): Promise<Record<string, unknown>> {
    const path = "/v1/auth/verify-email";
    return this.request<Record<string, unknown>>(
      'POST',
      path,
      body,
    );
  }

  // ──────────────────────────────────────────────────
  // Internal request helper
  // ──────────────────────────────────────────────────


  private async request<T>(
    method: string,
    path: string,
    body?: unknown,
  ): Promise<T> {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
    };

    if (this.token) {
      headers['Authorization'] = `Bearer ${this.token}`;
    }

    const response = await this.fetchFn(`${this.baseURL}${path}`, {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined,
    });

    if (!response.ok) {
      const errorBody = await response.json().catch(() => ({ error: response.statusText }));
      throw new AuthClientError(response.status, errorBody.error ?? 'Unknown error');
    }

    if (response.status === 204) {
      return undefined as T;
    }

    return response.json() as Promise<T>;
  }
}

export class AuthClientError extends Error {
  constructor(
    public readonly status: number,
    message: string,
  ) {
    super(message);
    this.name = 'AuthClientError';
  }
}

/** Create a new AuthSome client. */
export function createAuthClient(config: AuthClientConfig): AuthClient {
  return new AuthClient(config);
}

