// Code generated by authsome sdkgen. DO NOT EDIT.

export interface APIKey {
  app_id?: string;
  created_at?: string;
  expires_at?: string;
  id?: string;
  key_prefix?: string;
  last_used_at?: string;
  name?: string;
  scopes?: string[];
}

export interface AuthResponse {
  refresh_token: string;
  session_token: string;
  user: User;
}

export interface Device {
  created_at?: string;
  fingerprint?: string;
  id?: string;
  ip_address?: string;
  last_used_at?: string;
  name?: string;
  type?: string;
  user_agent?: string;
  user_id?: string;
}

export interface Error {
  code?: number;
  error: string;
}

export interface Invitation {
  created_at?: string;
  email?: string;
  expires_at?: string;
  id?: string;
  org_id?: string;
  role?: string;
  status?: string;
  token?: string;
}

export interface MFAEnrollment {
  id?: string;
  method?: string;
  otpauth_url?: string;
  secret?: string;
}

export interface Manifest {
  base_path?: string;
  endpoints?: Record<string, unknown>[];
  features?: Record<string, unknown>;
  version?: string;
}

export interface Member {
  created_at?: string;
  id?: string;
  org_id?: string;
  role?: string;
  updated_at?: string;
  user_id?: string;
}

export interface Organization {
  app_id?: string;
  created_at?: string;
  id?: string;
  logo?: string;
  metadata?: Record<string, unknown>;
  name?: string;
  slug?: string;
  updated_at?: string;
}

export interface Session {
  created_at?: string;
  expires_at?: string;
  id?: string;
  token?: string;
  user_id?: string;
}

export interface TokenResponse {
  expires_at: string;
  refresh_token: string;
  session_token: string;
}

export interface User {
  banned?: boolean;
  created_at?: string;
  email: string;
  email_verified?: boolean;
  id: string;
  image?: string;
  name?: string;
  phone?: string;
  updated_at?: string;
  username?: string;
}

// Request types for operations with bodies

export type AdminBanUserRequest = { reason?: string };

export type ChangePasswordRequest = { current_password: string; new_password: string };

export type ForgotPasswordRequest = { email: string };

export type CreateAPIKeyRequest = { expires_at?: string; name: string; scopes?: string[] };

export type MagicLinkSendRequest = { email: string };

export type MagicLinkVerifyRequest = { token: string };

export type UpdateMeRequest = { image?: string; name?: string; username?: string };

export type MfaChallengeRequest = { code: string; enrollment_id: string };

export type MfaEnrollRequest = { method?: string; phone?: string };

export type MfaRecoveryVerifyRequest = { code: string };

export type MfaSMSSendRequest = { enrollment_id: string };

export type MfaSMSVerifyRequest = { code: string; enrollment_id: string };

export type MfaVerifyRequest = { code: string };

export type CreateOrgRequest = { logo?: string; name: string; slug: string };

export type UpdateOrgRequest = { logo?: string; name?: string };

export type CreateInvitationRequest = { email: string; role: string };

export type AddMemberRequest = { role: string; user_id: string };

export type RefreshSessionRequest = { refresh_token: string };

export type ResetPasswordRequest = { new_password: string; token: string };

export type SignInRequest = { email?: string; password: string; username?: string };

export type SignUpRequest = { email: string; name?: string; password: string; username?: string };

export type SsoACSRequest = { RelayState?: string; SAMLResponse: string };

export type SsoCallbackRequest = { code: string; state: string };

export type VerifyEmailRequest = { token: string };
